[package]
name = "mr-kaffee-template"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = { version = "0.11.*", features = ["blocking"] }
clap = { version = "4.*", features = ["derive"] }
regex = "1.*"
